service: exchange-rate-lambda

frameworkVersion: "3"

provider:
  name: aws
  profile: personal-lambdas
  runtime: python3.9
  environment:
    NOTION_TOKEN: ${env:NOTION_TOKEN}
    NOTION_DB_ID_EXPENSES: ${env:NOTION_DB_ID_EXPENSES}
    NOTION_DB_ID_INCOME: ${env:NOTION_DB_ID_INCOME}

functions:
  updateExpense:
    handler: update_expenses_handler.update_expenses_handler
    events:
      - schedule: rate(1 day)

  updateIncome:
    handler: update_income_handler.update_income_handler
    events:
      - schedule: rate(1 day)

  createExchangeRateEntry:
    handler: create_exchange_rate_entry_handler.create_exchange_rate_entry_handler
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-python-requirements
